# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
name = "save-for-later"
handle = "save-for-later"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition
#
[extension.settings]
  [[extensions.settings.fields]]
  key = "title_custom"
  type = "single_line_text_field"
  name = "Title for section"
  description = "Enter a title for the section"
  [[extensions.settings.fields]]
    key = "button_custom"
    type = "single_line_text_field"
    name = "Title for button"
    description = "Enter a title for the button"
  [[extensions.settings.fields]]
    key = "text_login"
    type = "single_line_text_field"
    name = "Banner description"
    description = "Enter a description for login."
  [[extensions.settings.fields]]
    key = "text_get_cart"
    type = "single_line_text_field"
    name = "Banner description"
    description = "Enter a description for saving cart."
  [[extensions.settings.fields]]
    key = "collapsible"
    type = "boolean"
    name = "Show collapsible description."
    description = "Display controls to expand or collapse the banner description."
  [[extensions.settings.fields]]
    key = "status_custom"
    type = "single_line_text_field"
    name = "Section status"
    [[extensions.settings.fields.validations]]
        name = "choices"
        value = "[\"info\", \"success\", \"attention\", \"warning\", \"new\"]"


